import type { Plan } from "@/types/api";

function download(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function exportPlanAsJSON(plan: Plan) {
  download(
    `${slug(plan.name)}.json`,
    JSON.stringify(plan, null, 2),
    "application/json",
  );
}

export function exportPlanAsMarkdown(plan: Plan) {
  const lines: string[] = [];
  lines.push(`# ${plan.name}`);
  lines.push("");
  lines.push(`**Strategy:** ${plan.strategy}  `);
  lines.push(`**Graduation:** ${plan.summary?.graduation_term ?? "—"}  `);
  if (plan.summary?.career_alignment !== undefined) {
    lines.push(`**Career alignment:** ${(plan.summary.career_alignment * 100).toFixed(0)}%  `);
  }
  if (plan.summary?.total_credits !== undefined) {
    lines.push(`**Total credits planned:** ${plan.summary.total_credits}  `);
  }
  lines.push("");
  lines.push("## Semesters");
  for (const t of plan.terms) {
    lines.push("");
    lines.push(`### ${t.term} — ${t.total_credits} credits · workload ${t.workload_score}`);
    for (const c of t.courses) {
      lines.push(`- ${c}`);
    }
  }
  if (plan.warnings.length) {
    lines.push("");
    lines.push("## Warnings");
    for (const w of plan.warnings) {
      lines.push(`- **[${w.severity.toUpperCase()}] ${w.code}** — ${w.message}`);
    }
  }
  lines.push("");
  lines.push("_Generated by DegreePilot — sample data, not an official audit._");
  download(`${slug(plan.name)}.md`, lines.join("\n"), "text/markdown");
}

function slug(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}
