import type { Config } from "@docusaurus/types";

const config: Config = {
  title: "Knowledge Base",
  tagline: "Evidence-backed knowledge base generated by LoreGraph",
  url: "https://example.com",
  baseUrl: "/",
  onBrokenLinks: "warn",
  onBrokenMarkdownLinks: "warn",
  i18n: { defaultLocale: "en", locales: ["en"] },
  // Enable Mermaid rendering for the architecture/flow diagrams.
  markdown: { mermaid: true },
  themes: ["@docusaurus/theme-mermaid"],
  presets: [
    [
      "classic",
      {
        docs: { sidebarPath: "./sidebars.ts", routeBasePath: "/" },
        blog: false,
        theme: {}
      }
    ]
  ],
  themeConfig: {
    navbar: {
      title: "Knowledge Base",
      items: [{ type: "docSidebar", sidebarId: "docs", position: "left", label: "Docs" }]
    },
    footer: { style: "dark", copyright: "Generated by LoreGraph" }
  }
};

export default config;
