"""Columbia College Core Curriculum — curated overlay.

Hand-curated: CNF prereqs, categories, career tags, workload.
Split unchanged from the original app/seed/courses.py.
"""

CORE_COURSES: list[dict] = [
    # ============================================================
    # Columbia College Core Curriculum
    # ============================================================
    {
        "code": "ENGL CC1010",
        "title": "University Writing",
        "department": "ENGL",
        "credits": 3,
        "description": "Foundational university writing seminar — Core requirement.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_writing"],
        "career_tags": [],
    },
    {
        "code": "SCNC CC1000",
        "title": "Frontiers of Science",
        "department": "SCNC",
        "credits": 3,
        "description": "Required Core science seminar. Lectures + small sections; intro to scientific habits of mind.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        # Deliberately NOT tagged core_science: the Science Requirement is
        # "two courses *beyond* Frontiers", and that requirement now expands
        # from the core_science category at seed time.
        "categories": ["core_frontiers_science"],
        "career_tags": [],
    },
    {
        "code": "HUMA CC1001",
        "title": "Masterpieces of Western Literature and Philosophy I (Lit Hum I)",
        "department": "HUMA",
        "credits": 4,
        "description": "First half of the year-long Literature Humanities sequence. Homer through the Renaissance.",
        "workload_level": 3,
        "offered_terms": ["Fall"],
        "prerequisites": [],
        "categories": ["core_lit_hum"],
        "career_tags": [],
    },
    {
        "code": "HUMA CC1002",
        "title": "Masterpieces of Western Literature and Philosophy II (Lit Hum II)",
        "department": "HUMA",
        "credits": 4,
        "description": "Second half of the year-long Literature Humanities sequence. Cervantes to the present.",
        "workload_level": 3,
        "offered_terms": ["Spring"],
        "prerequisites": [["HUMA CC1001"]],
        "categories": ["core_lit_hum"],
        "career_tags": [],
    },
    {
        "code": "COCI CC1101",
        "title": "Introduction to Contemporary Civilization in the West I",
        "department": "COCI",
        "credits": 4,
        "description": "First half of the year-long Contemporary Civilization sequence — political and moral philosophy from Plato.",
        "workload_level": 3,
        "offered_terms": ["Fall"],
        "prerequisites": [],
        "categories": ["core_cc"],
        "career_tags": [],
    },
    {
        "code": "COCI CC1102",
        "title": "Introduction to Contemporary Civilization in the West II",
        "department": "COCI",
        "credits": 4,
        "description": "Second half of the year-long Contemporary Civilization sequence — Enlightenment to the present.",
        "workload_level": 3,
        "offered_terms": ["Spring"],
        "prerequisites": [["COCI CC1101"]],
        "categories": ["core_cc"],
        "career_tags": [],
    },
    {
        "code": "HUMA UN1121",
        "title": "Masterpieces of Western Art (Art Humanities)",
        "department": "HUMA",
        "credits": 3,
        "description": "Single-semester seminar in Western visual art — Core requirement.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_art_hum"],
        "career_tags": [],
    },
    {
        "code": "HUMA UN1123",
        "title": "Masterpieces of Western Music (Music Humanities)",
        "department": "HUMA",
        "credits": 3,
        "description": "Single-semester seminar in Western music — Core requirement.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_music_hum"],
        "career_tags": [],
    },
    # ---- Science Requirement (beyond Frontiers) ----
    {
        "code": "BIOL UN2005",
        "title": "Introductory Biology I",
        "department": "BIOL",
        "credits": 4,
        "description": "Cellular and molecular biology — counts toward the Core Science Requirement.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [],
        "categories": ["core_science"],
        "career_tags": ["research"],
    },
    {
        "code": "CHEM UN1403",
        "title": "General Chemistry I",
        "department": "CHEM",
        "credits": 4,
        "description": "Atomic structure, bonding, thermodynamics — Core Science Requirement.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [],
        "categories": ["core_science"],
        "career_tags": [],
    },
    {
        "code": "PHYS UN1401",
        "title": "Introduction to Mechanics and Thermodynamics",
        "department": "PHYS",
        "credits": 3,
        "description": "Calc-based mechanics + thermodynamics — Core Science Requirement.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["MATH UN1101"]],
        "categories": ["core_science"],
        "career_tags": ["research"],
    },
    {
        "code": "ASTR UN1403",
        "title": "Earth, Moon, and Planets",
        "department": "ASTR",
        "credits": 3,
        "description": "Planetary science survey — Core Science Requirement (no lab).",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_science"],
        "career_tags": [],
    },
    # ---- Global Core options (sample) ----
    {
        "code": "AHUM UN1399",
        "title": "Colloquium on Major Texts: East Asia",
        "department": "AHUM",
        "credits": 4,
        "description": "Major literary, philosophical and religious texts of East Asia — Global Core option.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_global"],
        "career_tags": [],
    },
    {
        "code": "AHUM UN1400",
        "title": "Colloquium on Major Texts: Middle East and India",
        "department": "AHUM",
        "credits": 4,
        "description": "Major texts of the Islamic world and South Asia — Global Core option.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_global"],
        "career_tags": [],
    },
    {
        "code": "HIST UN2702",
        "title": "Latin American History",
        "department": "HIST",
        "credits": 3,
        "description": "Survey of Latin American history — Global Core option.",
        "workload_level": 3,
        "offered_terms": ["Spring"],
        "prerequisites": [],
        "categories": ["core_global"],
        "career_tags": [],
    },
    # ---- Foreign Language (placeholder representing completion of Intermediate II) ----
    {
        "code": "LANG CC2102",
        "title": "Intermediate II (Foreign Language Requirement)",
        "department": "LANG",
        "credits": 4,
        "description": "Placeholder representing completion of the Intermediate II level of any approved language.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_language"],
        "career_tags": [],
    },
    # ---- Physical Education (pass/withdraw, ~1 cr each) ----
    {
        "code": "PHED UN1001",
        "title": "Physical Education I",
        "department": "PHED",
        "credits": 1,
        "description": "Required PE activity course (pass/withdraw).",
        "workload_level": 1,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_pe"],
        "career_tags": [],
    },
    {
        "code": "PHED UN1002",
        "title": "Physical Education II",
        "department": "PHED",
        "credits": 1,
        "description": "Required PE activity course (pass/withdraw).",
        "workload_level": 1,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_pe"],
        "career_tags": [],
    },

]
