"""Computer Science (undergraduate) + supporting math/stat — curated overlay.

Hand-curated: CNF prereqs, categories, career tags, workload.
Split unchanged from the original app/seed/courses.py.
"""

CS_COURSES: list[dict] = [
    # ============================================================
    # CS — intro / pre-intro
    # ============================================================
    {
        "code": "ENGI E1006",
        "title": "Introduction to Computing for Engineers and Applied Scientists",
        "department": "ENGI",
        "credits": 3,
        "description": "Python-based intro to computational problem-solving; a pre-intro path into CS for engineers.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["cs_pre_intro"],
        "career_tags": ["data", "swe"],
    },
    {
        "code": "COMS W1004",
        "title": "Introduction to Computer Science and Programming in Java",
        "department": "COMS",
        "credits": 3,
        "description": "Foundations of programming and problem-solving in Java; control flow, recursion, basic data structures.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["cs_intro"],
        "career_tags": ["swe"],
    },
    {
        "code": "COMS W1007",
        "title": "Honors Introduction to Computer Science",
        "department": "COMS",
        "credits": 3,
        "description": "Accelerated intro to CS in Java; expects programming background. Substitutes for W1004.",
        "workload_level": 3,
        "offered_terms": ["Fall"],
        "prerequisites": [],
        "categories": ["cs_intro"],
        "career_tags": ["swe", "research"],
    },
    # ============================================================
    # CS — core
    # ============================================================
    {
        "code": "COMS W3134",
        "title": "Data Structures in Java",
        "department": "COMS",
        "credits": 3,
        "description": "Lists, trees, hash tables, graphs, sorting & searching, algorithmic analysis in Java.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W1004", "COMS W1007"]],
        "categories": ["cs_core"],
        "career_tags": ["swe", "ai_ml", "systems"],
    },
    {
        "code": "COMS W3136",
        "title": "Data Structures with C/C++",
        "department": "COMS",
        "credits": 4,
        "description": "Equivalent to W3134, taught with C/C++; covers memory model + data structures.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W1004", "COMS W1007"]],
        "categories": ["cs_core"],
        "career_tags": ["swe", "systems"],
    },
    {
        "code": "COMS W3137",
        "title": "Honors Data Structures and Algorithms",
        "department": "COMS",
        "credits": 4,
        "description": "Accelerated data structures + algorithms; covers material spanning W3134 and W4231.",
        "workload_level": 5,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W1004", "COMS W1007"]],
        "categories": ["cs_core"],
        "career_tags": ["swe", "research"],
    },
    {
        "code": "COMS W3157",
        "title": "Advanced Programming",
        "department": "COMS",
        "credits": 4,
        "description": "C, Unix toolchain, shell, Make, debuggers, version control, modern software engineering practice.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3134", "COMS W3136", "COMS W3137"]],
        "categories": ["cs_core"],
        "career_tags": ["swe", "systems"],
    },
    {
        "code": "COMS W3203",
        "title": "Discrete Mathematics: Introduction to Combinatorics and Graph Theory",
        "department": "COMS",
        "credits": 3,
        "description": "Logic, proofs, combinatorics, graph theory, probability for computer scientists.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W1004", "COMS W1007"]],
        "categories": ["cs_core", "cs_theory"],
        "career_tags": ["research", "ai_ml"],
    },
    {
        "code": "COMS W3261",
        "title": "Computer Science Theory",
        "department": "COMS",
        "credits": 3,
        "description": "Automata, formal languages, Turing machines, undecidability, intro to complexity.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3203"]],
        "categories": ["cs_core", "cs_theory"],
        "career_tags": ["research"],
    },
    {
        "code": "CSEE W3827",
        "title": "Fundamentals of Computer Systems",
        "department": "CSEE",
        "credits": 3,
        "description": "Logic gates, ISA, datapath, memory hierarchy — from transistors to a working machine.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3134", "COMS W3136", "COMS W3137"]],
        "categories": ["cs_core", "cs_systems"],
        "career_tags": ["systems"],
    },

    # ============================================================
    # CS — Area Foundation courses (pick-3 list per CC bulletin)
    # ============================================================
    {
        "code": "COMS W4111",
        "title": "Introduction to Databases",
        "department": "COMS",
        "credits": 3,
        "description": "Relational model, SQL, query optimization, transactions, intro to NoSQL.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3134", "COMS W3136", "COMS W3137"]],
        "categories": ["cs_area_foundation", "cs_track_sys"],
        "career_tags": ["swe", "data", "product"],
    },
    {
        "code": "COMS W4115",
        "title": "Programming Languages and Translators",
        "department": "COMS",
        "credits": 3,
        "description": "Compiler construction: lexing, parsing, type systems, code generation.",
        "workload_level": 5,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W3157"], ["COMS W3261"]],
        "categories": ["cs_area_foundation", "cs_track_theory"],
        "career_tags": ["systems", "research"],
    },
    {
        "code": "COMS W4118",
        "title": "Operating Systems I",
        "department": "COMS",
        "credits": 3,
        "description": "Processes, threads, synchronization, file systems, virtual memory.",
        "workload_level": 5,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3157"], ["CSEE W3827"]],
        "categories": ["cs_area_foundation", "cs_track_sys"],
        "career_tags": ["systems", "swe"],
    },
    {
        "code": "COMS W4119",
        "title": "Computer Networks",
        "department": "COMS",
        "credits": 3,
        "description": "Layered protocol architectures, TCP/IP, routing, congestion control.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W3157"]],
        "categories": ["cs_area_foundation", "cs_track_sys"],
        "career_tags": ["systems", "security"],
    },
    {
        "code": "COMS W4156",
        "title": "Advanced Software Engineering",
        "department": "COMS",
        "credits": 3,
        "description": "Team project software engineering: spec, design, agile, testing, deployment.",
        "workload_level": 4,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W3157"]],
        "categories": ["cs_area_foundation", "cs_track_se"],
        "career_tags": ["swe", "product"],
    },
    {
        "code": "COMS W4170",
        "title": "User Interface Design",
        "department": "COMS",
        "credits": 3,
        "description": "Principles of UI design, design process, prototyping, evaluation.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3134", "COMS W3136", "COMS W3137"]],
        "categories": ["cs_area_foundation", "cs_track_se"],
        "career_tags": ["swe", "product"],
    },
    {
        "code": "COMS W4181",
        "title": "Security I",
        "department": "COMS",
        "credits": 3,
        "description": "Software, OS, and network security fundamentals; offense + defense.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W3157"]],
        "categories": ["cs_area_foundation"],
        "career_tags": ["security", "systems"],
    },
    {
        "code": "COMS W4231",
        "title": "Analysis of Algorithms I",
        "department": "COMS",
        "credits": 3,
        "description": "Greedy, divide-and-conquer, dynamic programming, NP-completeness, approximation.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3134", "COMS W3136", "COMS W3137"], ["COMS W3203"]],
        "categories": ["cs_area_foundation", "cs_theory", "cs_track_theory"],
        "career_tags": ["swe", "research", "quant"],
    },
    {
        "code": "COMS W4236",
        "title": "Introduction to Computational Complexity",
        "department": "COMS",
        "credits": 3,
        "description": "P, NP, PSPACE, reductions, randomized & interactive proofs.",
        "workload_level": 5,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4231"]],
        "categories": ["cs_area_foundation", "cs_track_theory"],
        "career_tags": ["research"],
    },
    {
        "code": "COMS W4701",
        "title": "Artificial Intelligence",
        "department": "COMS",
        "credits": 3,
        "description": "Search, knowledge representation, planning, learning, NLP overview.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3134", "COMS W3136", "COMS W3137"], ["COMS W3203"]],
        "categories": ["cs_area_foundation", "cs_track_ai"],
        "career_tags": ["ai_ml", "research"],
    },
    {
        "code": "COMS W4705",
        "title": "Natural Language Processing",
        "department": "COMS",
        "credits": 3,
        "description": "Language modeling, parsing, embeddings, transformers, applications.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W4701", "COMS W4771"]],
        "categories": ["cs_area_foundation", "cs_track_ai"],
        "career_tags": ["ai_ml", "research"],
    },
    {
        "code": "COMS W4731",
        "title": "Computer Vision",
        "department": "COMS",
        "credits": 3,
        "description": "Image formation, features, segmentation, detection, deep visual models.",
        "workload_level": 4,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4701", "COMS W4771"]],
        "categories": ["cs_area_foundation", "cs_track_ai"],
        "career_tags": ["ai_ml", "research"],
    },
    {
        "code": "COMS W4771",
        "title": "Machine Learning",
        "department": "COMS",
        "credits": 3,
        "description": "Supervised & unsupervised learning, generalization, kernels, intro to deep learning.",
        "workload_level": 5,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [
            ["COMS W3134", "COMS W3136", "COMS W3137"],
            ["MATH UN2010", "MATH UN2015", "COMS W3251", "APMA E3101"],
            ["STAT UN1201", "MATH UN2015", "IEOR E3658", "STAT GU4001"],
        ],
        "categories": ["cs_area_foundation", "cs_track_ai"],
        "career_tags": ["ai_ml", "quant", "data", "research"],
    },
    {
        "code": "COMS W4774",
        "title": "Unsupervised Learning",
        "department": "COMS",
        "credits": 3,
        "description": "Clustering, dimensionality reduction, generative models.",
        "workload_level": 4,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4771"]],
        "categories": ["cs_track_ai", "cs_elective"],
        "career_tags": ["ai_ml", "research"],
    },

    # ============================================================
    # CS — math options
    # ============================================================
    {
        "code": "MATH UN1101",
        "title": "Calculus I",
        "department": "MATH",
        "credits": 3,
        "description": "Limits, derivatives, basic integration.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["math_prereq"],
        "career_tags": [],
    },
    {
        "code": "MATH UN1102",
        "title": "Calculus II",
        "department": "MATH",
        "credits": 3,
        "description": "Integration techniques, sequences & series, intro to multivariate.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1101"]],
        "categories": ["math_prereq"],
        "career_tags": [],
    },
    {
        "code": "MATH UN1201",
        "title": "Calculus III",
        "department": "MATH",
        "credits": 3,
        "description": "Multivariable calculus: partial derivatives, multiple integrals, vector calculus.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1101", "MATH UN1102"]],
        "categories": ["math_calculus"],
        "career_tags": ["quant"],
    },
    {
        "code": "MATH UN1205",
        "title": "Accelerated Multivariable Calculus",
        "department": "MATH",
        "credits": 4,
        "description": "Single-semester multivariable calculus for strong calculus students.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["MATH UN1101"]],
        "categories": ["math_calculus"],
        "career_tags": ["quant", "research"],
    },
    {
        "code": "APMA E2000",
        "title": "Multivariable Calculus for Engineers and Applied Scientists",
        "department": "APMA",
        "credits": 4,
        "description": "Calculus III equivalent in the engineering school sequence.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1101"]],
        "categories": ["math_calculus"],
        "career_tags": [],
    },
    {
        "code": "MATH UN2010",
        "title": "Linear Algebra",
        "department": "MATH",
        "credits": 3,
        "description": "Vectors, matrices, linear maps, eigenvectors, applications.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1201", "MATH UN1205", "APMA E2000"]],
        "categories": ["math_linear_algebra"],
        "career_tags": ["ai_ml", "quant"],
    },
    {
        "code": "MATH UN2015",
        "title": "Linear Algebra and Probability for Data Science",
        "department": "MATH",
        "credits": 4,
        "description": "Combined linear algebra + probability for data science applications.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1101"]],
        "categories": ["math_linear_algebra", "math_probstat"],
        "career_tags": ["ai_ml", "data"],
    },
    {
        "code": "COMS W3251",
        "title": "Computational Linear Algebra",
        "department": "COMS",
        "credits": 3,
        "description": "Linear algebra emphasizing computation and applications in CS.",
        "workload_level": 3,
        "offered_terms": ["Spring"],
        "prerequisites": [["MATH UN1201", "MATH UN1205", "APMA E2000"]],
        "categories": ["math_linear_algebra"],
        "career_tags": ["ai_ml", "quant"],
    },
    {
        "code": "APMA E3101",
        "title": "Applied Linear Algebra",
        "department": "APMA",
        "credits": 3,
        "description": "Linear algebra for engineers and applied math.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1201", "MATH UN1205", "APMA E2000"]],
        "categories": ["math_linear_algebra"],
        "career_tags": ["ai_ml", "quant"],
    },
    {
        "code": "STAT UN1201",
        "title": "Calculus-Based Introduction to Statistics",
        "department": "STAT",
        "credits": 3,
        "description": "Probability, random variables, estimation, hypothesis testing.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1101"]],
        "categories": ["math_probstat"],
        "career_tags": ["ai_ml", "quant", "data"],
    },
    {
        "code": "STAT GU4001",
        "title": "Introduction to Probability and Statistics",
        "department": "STAT",
        "credits": 3,
        "description": "Probability foundations + statistics; upper-level option for the CS prob/stat requirement.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1201", "MATH UN1205"]],
        "categories": ["math_probstat"],
        "career_tags": ["quant", "ai_ml"],
    },
    {
        "code": "IEOR E3658",
        "title": "Probability for Engineers",
        "department": "IEOR",
        "credits": 3,
        "description": "Probability and stochastic models with engineering applications.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1201", "MATH UN1205", "APMA E2000"]],
        "categories": ["math_probstat"],
        "career_tags": ["quant", "data"],
    },

]
