"""Economics — curated overlay.

Hand-curated: CNF prereqs, categories, career tags, workload.
Split unchanged from the original app/seed/courses.py.
"""

ECON_COURSES: list[dict] = [
    # ============================================================
    # Economics
    # ============================================================
    {
        "code": "ECON UN1105",
        "title": "Principles of Economics",
        "department": "ECON",
        "credits": 4,
        "description": "Intro to micro and macro principles; gateway to upper-level economics.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["econ_core"],
        "career_tags": ["quant", "product"],
    },
    {
        "code": "ECON UN3211",
        "title": "Intermediate Microeconomics",
        "department": "ECON",
        "credits": 4,
        "description": "Consumer theory, firm behavior, market equilibrium, game theory intro.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["ECON UN1105"], ["MATH UN1101"], ["MATH UN1201", "MATH UN1205"]],
        "categories": ["econ_core", "econ_intermediate"],
        "career_tags": ["quant", "product"],
    },
    {
        "code": "ECON UN3213",
        "title": "Intermediate Macroeconomics",
        "department": "ECON",
        "credits": 4,
        "description": "Long-run growth, business cycles, monetary & fiscal policy.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["ECON UN1105"], ["MATH UN1101"]],
        "categories": ["econ_core", "econ_intermediate"],
        "career_tags": ["quant"],
    },
    {
        "code": "ECON UN3412",
        "title": "Introduction to Econometrics",
        "department": "ECON",
        "credits": 4,
        "description": "OLS, inference, panel methods, instrumental variables.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["ECON UN3211", "ECON UN3213"], ["MATH UN1201", "MATH UN1205"], ["STAT UN1201"]],
        "categories": ["econ_core", "econ_intermediate"],
        "career_tags": ["quant", "data", "ai_ml"],
    },
    {
        "code": "ECON UN3025",
        "title": "Financial Economics",
        "department": "ECON",
        "credits": 3,
        "description": "Asset pricing, portfolio theory, market efficiency.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["ECON UN3211"], ["STAT UN1201"]],
        "categories": ["econ_elective", "econ_finance"],
        "career_tags": ["quant"],
    },
    {
        "code": "ECON GU4280",
        "title": "Corporate Finance",
        "department": "ECON",
        "credits": 3,
        "description": "Capital structure, valuation, financing decisions, M&A.",
        "workload_level": 4,
        "offered_terms": ["Spring"],
        "prerequisites": [["ECON UN3211"], ["STAT UN1201"]],
        "categories": ["econ_elective", "econ_finance"],
        "career_tags": ["quant", "product"],
    },
    {
        "code": "ECON GU4370",
        "title": "Political Economy",
        "department": "ECON",
        "credits": 3,
        "description": "Economic analysis of political institutions and outcomes.",
        "workload_level": 3,
        "offered_terms": ["Fall"],
        "prerequisites": [["ECON UN3211"]],
        "categories": ["econ_elective"],
        "career_tags": ["research", "product"],
    },
    {
        "code": "ECON GU4918",
        "title": "Seminar in Econometrics",
        "department": "ECON",
        "credits": 4,
        "description": "Capstone-style seminar applying econometric methods to research questions.",
        "workload_level": 4,
        "offered_terms": ["Spring"],
        "prerequisites": [["ECON UN3412"]],
        "categories": ["econ_elective", "econ_seminar"],
        "career_tags": ["research", "quant"],
    },
]
