"""Graduate Computer Science (MS, 6000-level) — curated overlay.

Hand-curated: CNF prereqs, categories, career tags, workload.
Split unchanged from the original app/seed/courses.py.
"""

MS_COURSES: list[dict] = [
    # ============================================================
    # Graduate Computer Science (MS) — 6000-level
    # Categories: ms_track_ml, ms_track_systems, ms_track_theory, grad_elective
    # ============================================================
    {
        "code": "COMS E6111",
        "title": "Advanced Database Systems",
        "department": "COMS",
        "credits": 3,
        "description": "Query processing internals, transaction management, distributed and web-scale data systems.",
        "workload_level": 4,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4111"]],
        "categories": ["ms_track_systems"],
        "career_tags": ["data", "systems", "swe"],
    },
    {
        "code": "COMS E6118",
        "title": "Operating Systems II",
        "department": "COMS",
        "credits": 3,
        "description": "Advanced OS research topics: virtualization, kernel design, reliability, OS support for cloud.",
        "workload_level": 5,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4118"]],
        "categories": ["ms_track_systems"],
        "career_tags": ["systems", "swe"],
    },
    {
        "code": "COMS E6181",
        "title": "Advanced Internet Services",
        "department": "COMS",
        "credits": 3,
        "description": "Multimedia networking, mobile and IoT services, content delivery, real-time protocols.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W4119"]],
        "categories": ["ms_track_systems"],
        "career_tags": ["systems", "swe"],
    },
    {
        "code": "COMS E6156",
        "title": "Topics in Software Engineering: Cloud Computing",
        "department": "COMS",
        "credits": 3,
        "description": "Cloud-native architecture, microservices, DevOps, and large-scale SaaS engineering.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W4156"]],
        "categories": ["ms_track_systems"],
        "career_tags": ["swe", "product", "systems"],
    },
    {
        "code": "COMS E6232",
        "title": "Analysis of Algorithms II",
        "department": "COMS",
        "credits": 3,
        "description": "Advanced algorithm design: approximation, randomized, online, and spectral methods.",
        "workload_level": 5,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4231"]],
        "categories": ["ms_track_theory"],
        "career_tags": ["research", "quant"],
    },
    {
        "code": "COMS E6261",
        "title": "Advanced Cryptography",
        "department": "COMS",
        "credits": 3,
        "description": "Modern cryptographic constructions and proofs: zero-knowledge, MPC, lattices.",
        "workload_level": 5,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W4181", "COMS W4236"]],
        "categories": ["ms_track_theory"],
        "career_tags": ["security", "research"],
    },
    {
        "code": "COMS E6253",
        "title": "Advanced Topics in Computational Learning Theory",
        "department": "COMS",
        "credits": 3,
        "description": "PAC learning, boosting, online learning, and the theory behind modern ML.",
        "workload_level": 5,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4771", "COMS W4231"]],
        "categories": ["ms_track_ml", "ms_track_theory"],
        "career_tags": ["ai_ml", "research", "quant"],
    },
    {
        "code": "COMS E6772",
        "title": "Advanced Machine Perception",
        "department": "COMS",
        "credits": 3,
        "description": "Deep learning for perception: representation learning, vision transformers, multimodal models.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W4771"]],
        "categories": ["ms_track_ml"],
        "career_tags": ["ai_ml", "research"],
    },
    {
        "code": "COMS E6732",
        "title": "Computational Imaging",
        "department": "COMS",
        "credits": 3,
        "description": "Computational photography and imaging pipelines; joint optics + algorithm design.",
        "workload_level": 4,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4731"]],
        "categories": ["ms_track_ml"],
        "career_tags": ["ai_ml", "research"],
    },
    {
        "code": "COMS E6893",
        "title": "Big Data Analytics",
        "department": "COMS",
        "credits": 3,
        "description": "Large-scale data platforms (Spark, streaming), applied ML pipelines, analytics system design.",
        "workload_level": 3,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W4111"]],
        "categories": ["ms_track_ml", "grad_elective"],
        "career_tags": ["data", "ai_ml", "swe"],
    },
    {
        "code": "COMS E6998",
        "title": "Topics in Computer Science",
        "department": "COMS",
        "credits": 3,
        "description": "Rotating advanced graduate topics (recent offerings: LLMs, cloud security, robot learning).",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["grad_elective"],
        "career_tags": ["ai_ml", "research", "swe"],
    },
]
