"""Seed catalog — Columbia College Core Curriculum + Computer Science + Economics.

Curated from the Columbia Bulletin:
  - https://bulletin.columbia.edu/columbia-college/requirements-degree-bachelor-arts/
  - https://bulletin.columbia.edu/columbia-college/core-curriculum/
  - https://bulletin.columbia.edu/columbia-college/departments-instruction/computer-science/
  - https://bulletin.columbia.edu/columbia-college/departments-instruction/economics/

Course codes follow Columbia's canonical format (e.g. "COMS W1004", "MATH UN1101",
"HUMA CC1001"). Prerequisite chains are modeled in CNF (list of OR-groups). Term
offerings, credits, workload levels, and career tags are curated approximations —
clearly marked as sample data in the UI. Not an official catalog.
"""

from __future__ import annotations

# Categories used across the catalog & requirements:
#   cs_intro, cs_core, cs_theory, cs_systems, cs_area_foundation, cs_elective,
#   cs_track_ai, cs_track_sys, cs_track_se, cs_track_theory,
#   math_calculus, math_linear_algebra, math_probstat,
#   econ_core, econ_intermediate, econ_elective, econ_finance,
#
# Career tags: ai_ml, swe, systems, quant, data, security, research, product

CS_AND_ECON_COURSES: list[dict] = [
    # ============================================================
    # Columbia College Core Curriculum
    # ============================================================
    {
        "code": "ENGL CC1010",
        "title": "University Writing",
        "department": "ENGL",
        "credits": 3,
        "description": "Foundational university writing seminar — Core requirement.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_writing"],
        "career_tags": [],
    },
    {
        "code": "SCNC CC1000",
        "title": "Frontiers of Science",
        "department": "SCNC",
        "credits": 3,
        "description": "Required Core science seminar. Lectures + small sections; intro to scientific habits of mind.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_frontiers_science", "core_science"],
        "career_tags": [],
    },
    {
        "code": "HUMA CC1001",
        "title": "Masterpieces of Western Literature and Philosophy I (Lit Hum I)",
        "department": "HUMA",
        "credits": 4,
        "description": "First half of the year-long Literature Humanities sequence. Homer through the Renaissance.",
        "workload_level": 3,
        "offered_terms": ["Fall"],
        "prerequisites": [],
        "categories": ["core_lit_hum"],
        "career_tags": [],
    },
    {
        "code": "HUMA CC1002",
        "title": "Masterpieces of Western Literature and Philosophy II (Lit Hum II)",
        "department": "HUMA",
        "credits": 4,
        "description": "Second half of the year-long Literature Humanities sequence. Cervantes to the present.",
        "workload_level": 3,
        "offered_terms": ["Spring"],
        "prerequisites": [["HUMA CC1001"]],
        "categories": ["core_lit_hum"],
        "career_tags": [],
    },
    {
        "code": "COCI CC1101",
        "title": "Introduction to Contemporary Civilization in the West I",
        "department": "COCI",
        "credits": 4,
        "description": "First half of the year-long Contemporary Civilization sequence — political and moral philosophy from Plato.",
        "workload_level": 3,
        "offered_terms": ["Fall"],
        "prerequisites": [],
        "categories": ["core_cc"],
        "career_tags": [],
    },
    {
        "code": "COCI CC1102",
        "title": "Introduction to Contemporary Civilization in the West II",
        "department": "COCI",
        "credits": 4,
        "description": "Second half of the year-long Contemporary Civilization sequence — Enlightenment to the present.",
        "workload_level": 3,
        "offered_terms": ["Spring"],
        "prerequisites": [["COCI CC1101"]],
        "categories": ["core_cc"],
        "career_tags": [],
    },
    {
        "code": "HUMA UN1121",
        "title": "Masterpieces of Western Art (Art Humanities)",
        "department": "HUMA",
        "credits": 3,
        "description": "Single-semester seminar in Western visual art — Core requirement.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_art_hum"],
        "career_tags": [],
    },
    {
        "code": "HUMA UN1123",
        "title": "Masterpieces of Western Music (Music Humanities)",
        "department": "HUMA",
        "credits": 3,
        "description": "Single-semester seminar in Western music — Core requirement.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_music_hum"],
        "career_tags": [],
    },
    # ---- Science Requirement (beyond Frontiers) ----
    {
        "code": "BIOL UN2005",
        "title": "Introductory Biology I",
        "department": "BIOL",
        "credits": 4,
        "description": "Cellular and molecular biology — counts toward the Core Science Requirement.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [],
        "categories": ["core_science"],
        "career_tags": ["research"],
    },
    {
        "code": "CHEM UN1403",
        "title": "General Chemistry I",
        "department": "CHEM",
        "credits": 4,
        "description": "Atomic structure, bonding, thermodynamics — Core Science Requirement.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [],
        "categories": ["core_science"],
        "career_tags": [],
    },
    {
        "code": "PHYS UN1401",
        "title": "Introduction to Mechanics and Thermodynamics",
        "department": "PHYS",
        "credits": 3,
        "description": "Calc-based mechanics + thermodynamics — Core Science Requirement.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["MATH UN1101"]],
        "categories": ["core_science"],
        "career_tags": ["research"],
    },
    {
        "code": "ASTR UN1403",
        "title": "Earth, Moon, and Planets",
        "department": "ASTR",
        "credits": 3,
        "description": "Planetary science survey — Core Science Requirement (no lab).",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_science"],
        "career_tags": [],
    },
    # ---- Global Core options (sample) ----
    {
        "code": "AHUM UN1399",
        "title": "Colloquium on Major Texts: East Asia",
        "department": "AHUM",
        "credits": 4,
        "description": "Major literary, philosophical and religious texts of East Asia — Global Core option.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_global"],
        "career_tags": [],
    },
    {
        "code": "AHUM UN1400",
        "title": "Colloquium on Major Texts: Middle East and India",
        "department": "AHUM",
        "credits": 4,
        "description": "Major texts of the Islamic world and South Asia — Global Core option.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_global"],
        "career_tags": [],
    },
    {
        "code": "HIST UN2702",
        "title": "Latin American History",
        "department": "HIST",
        "credits": 3,
        "description": "Survey of Latin American history — Global Core option.",
        "workload_level": 3,
        "offered_terms": ["Spring"],
        "prerequisites": [],
        "categories": ["core_global"],
        "career_tags": [],
    },
    # ---- Foreign Language (placeholder representing completion of Intermediate II) ----
    {
        "code": "LANG CC2102",
        "title": "Intermediate II (Foreign Language Requirement)",
        "department": "LANG",
        "credits": 4,
        "description": "Placeholder representing completion of the Intermediate II level of any approved language.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_language"],
        "career_tags": [],
    },
    # ---- Physical Education (pass/withdraw, ~1 cr each) ----
    {
        "code": "PHED UN1001",
        "title": "Physical Education I",
        "department": "PHED",
        "credits": 1,
        "description": "Required PE activity course (pass/withdraw).",
        "workload_level": 1,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_pe"],
        "career_tags": [],
    },
    {
        "code": "PHED UN1002",
        "title": "Physical Education II",
        "department": "PHED",
        "credits": 1,
        "description": "Required PE activity course (pass/withdraw).",
        "workload_level": 1,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["core_pe"],
        "career_tags": [],
    },

    # ============================================================
    # CS — intro / pre-intro
    # ============================================================
    {
        "code": "ENGI E1006",
        "title": "Introduction to Computing for Engineers and Applied Scientists",
        "department": "ENGI",
        "credits": 3,
        "description": "Python-based intro to computational problem-solving; a pre-intro path into CS for engineers.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["cs_pre_intro"],
        "career_tags": ["data", "swe"],
    },
    {
        "code": "COMS W1004",
        "title": "Introduction to Computer Science and Programming in Java",
        "department": "COMS",
        "credits": 3,
        "description": "Foundations of programming and problem-solving in Java; control flow, recursion, basic data structures.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["cs_intro"],
        "career_tags": ["swe"],
    },
    {
        "code": "COMS W1007",
        "title": "Honors Introduction to Computer Science",
        "department": "COMS",
        "credits": 3,
        "description": "Accelerated intro to CS in Java; expects programming background. Substitutes for W1004.",
        "workload_level": 3,
        "offered_terms": ["Fall"],
        "prerequisites": [],
        "categories": ["cs_intro"],
        "career_tags": ["swe", "research"],
    },
    # ============================================================
    # CS — core
    # ============================================================
    {
        "code": "COMS W3134",
        "title": "Data Structures in Java",
        "department": "COMS",
        "credits": 3,
        "description": "Lists, trees, hash tables, graphs, sorting & searching, algorithmic analysis in Java.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W1004", "COMS W1007"]],
        "categories": ["cs_core"],
        "career_tags": ["swe", "ai_ml", "systems"],
    },
    {
        "code": "COMS W3136",
        "title": "Data Structures with C/C++",
        "department": "COMS",
        "credits": 4,
        "description": "Equivalent to W3134, taught with C/C++; covers memory model + data structures.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W1004", "COMS W1007"]],
        "categories": ["cs_core"],
        "career_tags": ["swe", "systems"],
    },
    {
        "code": "COMS W3137",
        "title": "Honors Data Structures and Algorithms",
        "department": "COMS",
        "credits": 4,
        "description": "Accelerated data structures + algorithms; covers material spanning W3134 and W4231.",
        "workload_level": 5,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W1004", "COMS W1007"]],
        "categories": ["cs_core"],
        "career_tags": ["swe", "research"],
    },
    {
        "code": "COMS W3157",
        "title": "Advanced Programming",
        "department": "COMS",
        "credits": 4,
        "description": "C, Unix toolchain, shell, Make, debuggers, version control, modern software engineering practice.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3134", "COMS W3136", "COMS W3137"]],
        "categories": ["cs_core"],
        "career_tags": ["swe", "systems"],
    },
    {
        "code": "COMS W3203",
        "title": "Discrete Mathematics: Introduction to Combinatorics and Graph Theory",
        "department": "COMS",
        "credits": 3,
        "description": "Logic, proofs, combinatorics, graph theory, probability for computer scientists.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W1004", "COMS W1007"]],
        "categories": ["cs_core", "cs_theory"],
        "career_tags": ["research", "ai_ml"],
    },
    {
        "code": "COMS W3261",
        "title": "Computer Science Theory",
        "department": "COMS",
        "credits": 3,
        "description": "Automata, formal languages, Turing machines, undecidability, intro to complexity.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3203"]],
        "categories": ["cs_core", "cs_theory"],
        "career_tags": ["research"],
    },
    {
        "code": "CSEE W3827",
        "title": "Fundamentals of Computer Systems",
        "department": "CSEE",
        "credits": 3,
        "description": "Logic gates, ISA, datapath, memory hierarchy — from transistors to a working machine.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3134", "COMS W3136", "COMS W3137"]],
        "categories": ["cs_core", "cs_systems"],
        "career_tags": ["systems"],
    },

    # ============================================================
    # CS — Area Foundation courses (pick-3 list per CC bulletin)
    # ============================================================
    {
        "code": "COMS W4111",
        "title": "Introduction to Databases",
        "department": "COMS",
        "credits": 3,
        "description": "Relational model, SQL, query optimization, transactions, intro to NoSQL.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3134", "COMS W3136", "COMS W3137"]],
        "categories": ["cs_area_foundation", "cs_track_sys"],
        "career_tags": ["swe", "data", "product"],
    },
    {
        "code": "COMS W4115",
        "title": "Programming Languages and Translators",
        "department": "COMS",
        "credits": 3,
        "description": "Compiler construction: lexing, parsing, type systems, code generation.",
        "workload_level": 5,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W3157"], ["COMS W3261"]],
        "categories": ["cs_area_foundation", "cs_track_theory"],
        "career_tags": ["systems", "research"],
    },
    {
        "code": "COMS W4118",
        "title": "Operating Systems I",
        "department": "COMS",
        "credits": 3,
        "description": "Processes, threads, synchronization, file systems, virtual memory.",
        "workload_level": 5,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3157"], ["CSEE W3827"]],
        "categories": ["cs_area_foundation", "cs_track_sys"],
        "career_tags": ["systems", "swe"],
    },
    {
        "code": "COMS W4119",
        "title": "Computer Networks",
        "department": "COMS",
        "credits": 3,
        "description": "Layered protocol architectures, TCP/IP, routing, congestion control.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W3157"]],
        "categories": ["cs_area_foundation", "cs_track_sys"],
        "career_tags": ["systems", "security"],
    },
    {
        "code": "COMS W4156",
        "title": "Advanced Software Engineering",
        "department": "COMS",
        "credits": 3,
        "description": "Team project software engineering: spec, design, agile, testing, deployment.",
        "workload_level": 4,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W3157"]],
        "categories": ["cs_area_foundation", "cs_track_se"],
        "career_tags": ["swe", "product"],
    },
    {
        "code": "COMS W4170",
        "title": "User Interface Design",
        "department": "COMS",
        "credits": 3,
        "description": "Principles of UI design, design process, prototyping, evaluation.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3134", "COMS W3136", "COMS W3137"]],
        "categories": ["cs_area_foundation", "cs_track_se"],
        "career_tags": ["swe", "product"],
    },
    {
        "code": "COMS W4181",
        "title": "Security I",
        "department": "COMS",
        "credits": 3,
        "description": "Software, OS, and network security fundamentals; offense + defense.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W3157"]],
        "categories": ["cs_area_foundation"],
        "career_tags": ["security", "systems"],
    },
    {
        "code": "COMS W4231",
        "title": "Analysis of Algorithms I",
        "department": "COMS",
        "credits": 3,
        "description": "Greedy, divide-and-conquer, dynamic programming, NP-completeness, approximation.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3134", "COMS W3136", "COMS W3137"], ["COMS W3203"]],
        "categories": ["cs_area_foundation", "cs_theory", "cs_track_theory"],
        "career_tags": ["swe", "research", "quant"],
    },
    {
        "code": "COMS W4236",
        "title": "Introduction to Computational Complexity",
        "department": "COMS",
        "credits": 3,
        "description": "P, NP, PSPACE, reductions, randomized & interactive proofs.",
        "workload_level": 5,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4231"]],
        "categories": ["cs_area_foundation", "cs_track_theory"],
        "career_tags": ["research"],
    },
    {
        "code": "COMS W4701",
        "title": "Artificial Intelligence",
        "department": "COMS",
        "credits": 3,
        "description": "Search, knowledge representation, planning, learning, NLP overview.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W3134", "COMS W3136", "COMS W3137"], ["COMS W3203"]],
        "categories": ["cs_area_foundation", "cs_track_ai"],
        "career_tags": ["ai_ml", "research"],
    },
    {
        "code": "COMS W4705",
        "title": "Natural Language Processing",
        "department": "COMS",
        "credits": 3,
        "description": "Language modeling, parsing, embeddings, transformers, applications.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W4701", "COMS W4771"]],
        "categories": ["cs_area_foundation", "cs_track_ai"],
        "career_tags": ["ai_ml", "research"],
    },
    {
        "code": "COMS W4731",
        "title": "Computer Vision",
        "department": "COMS",
        "credits": 3,
        "description": "Image formation, features, segmentation, detection, deep visual models.",
        "workload_level": 4,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4701", "COMS W4771"]],
        "categories": ["cs_area_foundation", "cs_track_ai"],
        "career_tags": ["ai_ml", "research"],
    },
    {
        "code": "COMS W4771",
        "title": "Machine Learning",
        "department": "COMS",
        "credits": 3,
        "description": "Supervised & unsupervised learning, generalization, kernels, intro to deep learning.",
        "workload_level": 5,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [
            ["COMS W3134", "COMS W3136", "COMS W3137"],
            ["MATH UN2010", "MATH UN2015", "COMS W3251", "APMA E3101"],
            ["STAT UN1201", "MATH UN2015", "IEOR E3658", "STAT GU4001"],
        ],
        "categories": ["cs_area_foundation", "cs_track_ai"],
        "career_tags": ["ai_ml", "quant", "data", "research"],
    },
    {
        "code": "COMS W4774",
        "title": "Unsupervised Learning",
        "department": "COMS",
        "credits": 3,
        "description": "Clustering, dimensionality reduction, generative models.",
        "workload_level": 4,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4771"]],
        "categories": ["cs_track_ai", "cs_elective"],
        "career_tags": ["ai_ml", "research"],
    },

    # ============================================================
    # CS — math options
    # ============================================================
    {
        "code": "MATH UN1101",
        "title": "Calculus I",
        "department": "MATH",
        "credits": 3,
        "description": "Limits, derivatives, basic integration.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["math_prereq"],
        "career_tags": [],
    },
    {
        "code": "MATH UN1102",
        "title": "Calculus II",
        "department": "MATH",
        "credits": 3,
        "description": "Integration techniques, sequences & series, intro to multivariate.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1101"]],
        "categories": ["math_prereq"],
        "career_tags": [],
    },
    {
        "code": "MATH UN1201",
        "title": "Calculus III",
        "department": "MATH",
        "credits": 3,
        "description": "Multivariable calculus: partial derivatives, multiple integrals, vector calculus.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1101", "MATH UN1102"]],
        "categories": ["math_calculus"],
        "career_tags": ["quant"],
    },
    {
        "code": "MATH UN1205",
        "title": "Accelerated Multivariable Calculus",
        "department": "MATH",
        "credits": 4,
        "description": "Single-semester multivariable calculus for strong calculus students.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["MATH UN1101"]],
        "categories": ["math_calculus"],
        "career_tags": ["quant", "research"],
    },
    {
        "code": "APMA E2000",
        "title": "Multivariable Calculus for Engineers and Applied Scientists",
        "department": "APMA",
        "credits": 4,
        "description": "Calculus III equivalent in the engineering school sequence.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1101"]],
        "categories": ["math_calculus"],
        "career_tags": [],
    },
    {
        "code": "MATH UN2010",
        "title": "Linear Algebra",
        "department": "MATH",
        "credits": 3,
        "description": "Vectors, matrices, linear maps, eigenvectors, applications.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1201", "MATH UN1205", "APMA E2000"]],
        "categories": ["math_linear_algebra"],
        "career_tags": ["ai_ml", "quant"],
    },
    {
        "code": "MATH UN2015",
        "title": "Linear Algebra and Probability for Data Science",
        "department": "MATH",
        "credits": 4,
        "description": "Combined linear algebra + probability for data science applications.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1101"]],
        "categories": ["math_linear_algebra", "math_probstat"],
        "career_tags": ["ai_ml", "data"],
    },
    {
        "code": "COMS W3251",
        "title": "Computational Linear Algebra",
        "department": "COMS",
        "credits": 3,
        "description": "Linear algebra emphasizing computation and applications in CS.",
        "workload_level": 3,
        "offered_terms": ["Spring"],
        "prerequisites": [["MATH UN1201", "MATH UN1205", "APMA E2000"]],
        "categories": ["math_linear_algebra"],
        "career_tags": ["ai_ml", "quant"],
    },
    {
        "code": "APMA E3101",
        "title": "Applied Linear Algebra",
        "department": "APMA",
        "credits": 3,
        "description": "Linear algebra for engineers and applied math.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1201", "MATH UN1205", "APMA E2000"]],
        "categories": ["math_linear_algebra"],
        "career_tags": ["ai_ml", "quant"],
    },
    {
        "code": "STAT UN1201",
        "title": "Calculus-Based Introduction to Statistics",
        "department": "STAT",
        "credits": 3,
        "description": "Probability, random variables, estimation, hypothesis testing.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1101"]],
        "categories": ["math_probstat"],
        "career_tags": ["ai_ml", "quant", "data"],
    },
    {
        "code": "STAT GU4001",
        "title": "Introduction to Probability and Statistics",
        "department": "STAT",
        "credits": 3,
        "description": "Probability foundations + statistics; upper-level option for the CS prob/stat requirement.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1201", "MATH UN1205"]],
        "categories": ["math_probstat"],
        "career_tags": ["quant", "ai_ml"],
    },
    {
        "code": "IEOR E3658",
        "title": "Probability for Engineers",
        "department": "IEOR",
        "credits": 3,
        "description": "Probability and stochastic models with engineering applications.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["MATH UN1201", "MATH UN1205", "APMA E2000"]],
        "categories": ["math_probstat"],
        "career_tags": ["quant", "data"],
    },

    # ============================================================
    # Economics
    # ============================================================
    {
        "code": "ECON UN1105",
        "title": "Principles of Economics",
        "department": "ECON",
        "credits": 4,
        "description": "Intro to micro and macro principles; gateway to upper-level economics.",
        "workload_level": 2,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["econ_core"],
        "career_tags": ["quant", "product"],
    },
    {
        "code": "ECON UN3211",
        "title": "Intermediate Microeconomics",
        "department": "ECON",
        "credits": 4,
        "description": "Consumer theory, firm behavior, market equilibrium, game theory intro.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["ECON UN1105"], ["MATH UN1101"], ["MATH UN1201", "MATH UN1205"]],
        "categories": ["econ_core", "econ_intermediate"],
        "career_tags": ["quant", "product"],
    },
    {
        "code": "ECON UN3213",
        "title": "Intermediate Macroeconomics",
        "department": "ECON",
        "credits": 4,
        "description": "Long-run growth, business cycles, monetary & fiscal policy.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["ECON UN1105"], ["MATH UN1101"]],
        "categories": ["econ_core", "econ_intermediate"],
        "career_tags": ["quant"],
    },
    {
        "code": "ECON UN3412",
        "title": "Introduction to Econometrics",
        "department": "ECON",
        "credits": 4,
        "description": "OLS, inference, panel methods, instrumental variables.",
        "workload_level": 4,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["ECON UN3211", "ECON UN3213"], ["MATH UN1201", "MATH UN1205"], ["STAT UN1201"]],
        "categories": ["econ_core", "econ_intermediate"],
        "career_tags": ["quant", "data", "ai_ml"],
    },
    {
        "code": "ECON UN3025",
        "title": "Financial Economics",
        "department": "ECON",
        "credits": 3,
        "description": "Asset pricing, portfolio theory, market efficiency.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["ECON UN3211"], ["STAT UN1201"]],
        "categories": ["econ_elective", "econ_finance"],
        "career_tags": ["quant"],
    },
    {
        "code": "ECON GU4280",
        "title": "Corporate Finance",
        "department": "ECON",
        "credits": 3,
        "description": "Capital structure, valuation, financing decisions, M&A.",
        "workload_level": 4,
        "offered_terms": ["Spring"],
        "prerequisites": [["ECON UN3211"], ["STAT UN1201"]],
        "categories": ["econ_elective", "econ_finance"],
        "career_tags": ["quant", "product"],
    },
    {
        "code": "ECON GU4370",
        "title": "Political Economy",
        "department": "ECON",
        "credits": 3,
        "description": "Economic analysis of political institutions and outcomes.",
        "workload_level": 3,
        "offered_terms": ["Fall"],
        "prerequisites": [["ECON UN3211"]],
        "categories": ["econ_elective"],
        "career_tags": ["research", "product"],
    },
    {
        "code": "ECON GU4918",
        "title": "Seminar in Econometrics",
        "department": "ECON",
        "credits": 4,
        "description": "Capstone-style seminar applying econometric methods to research questions.",
        "workload_level": 4,
        "offered_terms": ["Spring"],
        "prerequisites": [["ECON UN3412"]],
        "categories": ["econ_elective", "econ_seminar"],
        "career_tags": ["research", "quant"],
    },
    # ============================================================
    # Graduate Computer Science (MS) — 6000-level
    # Categories: ms_track_ml, ms_track_systems, ms_track_theory, grad_elective
    # ============================================================
    {
        "code": "COMS E6111",
        "title": "Advanced Database Systems",
        "department": "COMS",
        "credits": 3,
        "description": "Query processing internals, transaction management, distributed and web-scale data systems.",
        "workload_level": 4,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4111"]],
        "categories": ["ms_track_systems"],
        "career_tags": ["data", "systems", "swe"],
    },
    {
        "code": "COMS E6118",
        "title": "Operating Systems II",
        "department": "COMS",
        "credits": 3,
        "description": "Advanced OS research topics: virtualization, kernel design, reliability, OS support for cloud.",
        "workload_level": 5,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4118"]],
        "categories": ["ms_track_systems"],
        "career_tags": ["systems", "swe"],
    },
    {
        "code": "COMS E6181",
        "title": "Advanced Internet Services",
        "department": "COMS",
        "credits": 3,
        "description": "Multimedia networking, mobile and IoT services, content delivery, real-time protocols.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W4119"]],
        "categories": ["ms_track_systems"],
        "career_tags": ["systems", "swe"],
    },
    {
        "code": "COMS E6156",
        "title": "Topics in Software Engineering: Cloud Computing",
        "department": "COMS",
        "credits": 3,
        "description": "Cloud-native architecture, microservices, DevOps, and large-scale SaaS engineering.",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [["COMS W4156"]],
        "categories": ["ms_track_systems"],
        "career_tags": ["swe", "product", "systems"],
    },
    {
        "code": "COMS E6232",
        "title": "Analysis of Algorithms II",
        "department": "COMS",
        "credits": 3,
        "description": "Advanced algorithm design: approximation, randomized, online, and spectral methods.",
        "workload_level": 5,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4231"]],
        "categories": ["ms_track_theory"],
        "career_tags": ["research", "quant"],
    },
    {
        "code": "COMS E6261",
        "title": "Advanced Cryptography",
        "department": "COMS",
        "credits": 3,
        "description": "Modern cryptographic constructions and proofs: zero-knowledge, MPC, lattices.",
        "workload_level": 5,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W4181", "COMS W4236"]],
        "categories": ["ms_track_theory"],
        "career_tags": ["security", "research"],
    },
    {
        "code": "COMS E6253",
        "title": "Advanced Topics in Computational Learning Theory",
        "department": "COMS",
        "credits": 3,
        "description": "PAC learning, boosting, online learning, and the theory behind modern ML.",
        "workload_level": 5,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4771", "COMS W4231"]],
        "categories": ["ms_track_ml", "ms_track_theory"],
        "career_tags": ["ai_ml", "research", "quant"],
    },
    {
        "code": "COMS E6772",
        "title": "Advanced Machine Perception",
        "department": "COMS",
        "credits": 3,
        "description": "Deep learning for perception: representation learning, vision transformers, multimodal models.",
        "workload_level": 4,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W4771"]],
        "categories": ["ms_track_ml"],
        "career_tags": ["ai_ml", "research"],
    },
    {
        "code": "COMS E6732",
        "title": "Computational Imaging",
        "department": "COMS",
        "credits": 3,
        "description": "Computational photography and imaging pipelines; joint optics + algorithm design.",
        "workload_level": 4,
        "offered_terms": ["Spring"],
        "prerequisites": [["COMS W4731"]],
        "categories": ["ms_track_ml"],
        "career_tags": ["ai_ml", "research"],
    },
    {
        "code": "COMS E6893",
        "title": "Big Data Analytics",
        "department": "COMS",
        "credits": 3,
        "description": "Large-scale data platforms (Spark, streaming), applied ML pipelines, analytics system design.",
        "workload_level": 3,
        "offered_terms": ["Fall"],
        "prerequisites": [["COMS W4111"]],
        "categories": ["ms_track_ml", "grad_elective"],
        "career_tags": ["data", "ai_ml", "swe"],
    },
    {
        "code": "COMS E6998",
        "title": "Topics in Computer Science",
        "department": "COMS",
        "credits": 3,
        "description": "Rotating advanced graduate topics (recent offerings: LLMs, cloud security, robot learning).",
        "workload_level": 3,
        "offered_terms": ["Fall", "Spring"],
        "prerequisites": [],
        "categories": ["grad_elective"],
        "career_tags": ["ai_ml", "research", "swe"],
    },
]
